version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISPLAY: ":0"
      DEBIAN_FRONTEND: "noninteractive"
    command: npm run start
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/proj
      - /proj/node_modules
    ports:
        - "4200:4200"
