version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - .:/proj
      - /proj/node_modules
    ports:
        - "4200:4200"
